language: java

sudo: false

script: mvn -Dhttpclient.version=$HTTPCLIENT_VERSION -Dhttpclient.test.version=$HTTPCLIENT_TEST_VERSION clean verify javadoc:javadoc

jdk:
  - openjdk7
  - oraclejdk8

# We use httpclient test jar providing LocalTestServer.java; no longer in 4.4+.

env:
  - HTTPCLIENT_VERSION=4.1    HTTPCLIENT_TEST_VERSION=4.1
  - HTTPCLIENT_VERSION=4.2    HTTPCLIENT_TEST_VERSION=4.2
  - HTTPCLIENT_VERSION=4.3.6  HTTPCLIENT_TEST_VERSION=4.3.5
  - HTTPCLIENT_VERSION=4.4.1  HTTPCLIENT_TEST_VERSION=4.3.5
  - HTTPCLIENT_VERSION=4.5.2  HTTPCLIENT_TEST_VERSION=4.3.5

notifications:
  email:
    - dsmiley@apache.org